# Generated by Django 5.0.1 on 2024-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0003_semester_complete_date_semester_gpa_semester_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='avarage_mark',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
