# Generated by Django 5.0.1 on 2024-02-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0004_semester_avarage_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='avarage_mark',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='complete_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='point',
        ),
    ]
